apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-virtualization
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/pindych-michal/argocd-demo.git
    targetRevision: main
    path: apps/openshift-virtualization
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    # nadal brak "automated" -> sync wyzwalasz ręcznie z GUI
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  ignoreDifferences:
    - group: operators.coreos.com
      kind: Subscription
      jsonPointers:
        - /spec/startingCSV
    - group: hco.kubevirt.io
      kind: HyperConverged
      jsonPointers:
        - /spec
