apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>nginx-demo</title></head>
    <body>
      <h1>nginx-demo działa!</h1>
      <p>Deployment w namespace deployment-test</p>
    </body>
    </html>
  healthz: |
    OK
